tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "autoconf"
brew "coreutils"
brew "bash-completion"
brew "exercism"
brew "gnupg"
brew "grip"
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "wxmac"
brew "z"
brew "heroku/brew/heroku"
cask "docker"
