[tools]
ruby = "3.2.2"
node = "18.13.0"
erlang = "26.1.1"
elixir = "1.15.6-otp-26"
rust = "1.56.0"
helm = "3.7.1"

[settings]
idiomatic_version_file_enable_tools = []
# Legacy version file support to read .tool-versions files
legacy_version_file = true

